### ISSUE TITLE
How to config this for openpiton?

### ISSUE THREAD

**Issue by zhb9103** [PrincetonUniversity/piton-linux#3]
Hi, I want to use this for openpiton multi-core bringup. How to use this linux package?
1. How to config this for ariane core of piton?
2. Where is the compiler for compiling image for ariane core of piton?
3. How to burn generated image into SD card(any guide for this)?

Thanks!

**Comment by Jbalkind** [comment]
I am for some reason not subscribed to new issues on this repo so I hadn't seen your issue. I would suggest you check out https://github.com/Jbalkind/ariane-sdk/tree/openpiton-opensbi (the specific openpiton-opensbi branch I point to) for building an opensbi+kernel+buildroot rootfs blob and instructions on how to put that on the SD card.

**Comment by zhb9103** [comment]
Ok, thank you very much!
